### ISSUE TITLE
Problems with margin & padding on a column block

### ISSUE THREAD

**Issue by sdelon** [greghunt/tailpress#8]
Hello Greg,

I have a problem when I add classes related to margin or padding. They are simply not taken into account. As you can see on the attachment, I add them on a column block.

![Screenshot 2023-01-08 10 15 16](https://user-images.githubusercontent.com/53929569/211188728-b19678ba-4a2c-499d-a5a6-dd6af83b94d5.png)

In pure css addition, these margins work correctly, so I don't quite understand what is blocking when adding them with tailwind classes.

Thank you for this great and very useful plugin :-)
Have a great day !

Stephanie

**Comment by greghunt** [comment]
Hi @sdelon , I believe this is because WordPress admin styles are scoped very specifically and override the TW utility classes. In this case, you can try adding `!` to your margin class to make sure it's considered important and overrides WP.
